'use strict';
const el=id=>document.getElementById(id);
const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const validUrl=url=>{try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='www.dropbox.com'?u.href:'#';}catch{return '#';}};
const safeImage=url=>typeof url==='string'&&(/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(url)||/^\/images\/[a-f0-9]+\.jpg$/.test(url))?url:'';
let data,filter='all',current=null,index=0,photos=[];
function showPhoto(){const p=photos[index];el('viewer').src=safeImage(p.preview);el('viewer').alt=current.title+' — '+(index+1);el('position').textContent=(index+1)+' / '+photos.length;el('prev').disabled=index===0;el('next').disabled=index===photos.length-1;el('thumbs').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('selected',i===index);b.setAttribute('aria-pressed',String(i===index));});}
function openProduct(p){current=p;index=0;photos=[p.cover,...(p.status==='sold'?[]:p.photos)];el('modalTitle').textContent=p.title;el('modalSub').textContent=p.brand+' · '+p.model+' · '+(p.status==='sold'?'Sold':p.status==='in_stock'?'In Stock':'Inbound');el('thumbs').replaceChildren();photos.forEach((photo,i)=>{const b=node('button');b.setAttribute('aria-label','Photo '+(i+1));const img=node('img');img.src=safeImage(photo.preview);img.alt='Photo '+(i+1);img.loading='lazy';b.append(img);b.addEventListener('click',()=>{index=i;showPhoto();});el('thumbs').append(b);});el('thumbs').hidden=photos.length===1;document.querySelector('.swipehint').hidden=photos.length===1;el('folderLink').hidden=p.status==='sold';el('folderLink').href=validUrl(p.folder_url);el('photoNote').textContent=p.status==='sold'?'Archived '+new Date(p.archived_at).toLocaleDateString()+'. Only the cover photo is retained.':p.photo_note||'';showPhoto();el('modal').showModal();}
function render(){const query=el('search').value.toLowerCase().trim(),brand=el('brand').value;const list=data.products.filter(p=>(filter==='all'?p.status!=='sold':p.status===filter)&&(!brand||p.brand===brand)&&[p.title,p.brand,p.model,p.stock_number].join(' ').toLowerCase().includes(query));list.sort((a,b)=>filter==='sold'?(a.brand.localeCompare(b.brand)||a.model.localeCompare(b.model)||a.title.localeCompare(b.title)):(Number(a.status==='inbound')-Number(b.status==='inbound')||a.title.localeCompare(b.title)));el('grid').replaceChildren();el('resultcount').textContent=list.length+' '+(filter==='sold'?'archived ':'')+'watch'+(list.length===1?'':'es');let lastBrand='',lastModel='';for(const p of list){if(filter==='sold'){if(p.brand!==lastBrand){el('grid').append(node('h2','brandgroup',p.brand));lastBrand=p.brand;lastModel='';}if(p.model!==lastModel){el('grid').append(node('h3','modelgroup',p.model));lastModel=p.model;}}const card=node('article','card'),pic=node('button','picture'),img=node('img');pic.setAttribute('aria-label','View photos: '+p.title);img.src=safeImage(p.cover.preview);img.alt=p.title;img.loading='lazy';pic.append(img,node('span','badge '+p.status,p.status==='sold'?'Sold':p.status==='in_stock'?'In Stock':'Inbound'));pic.addEventListener('click',()=>openProduct(p));const content=node('div','content');content.append(node('div','maker',p.brand),node('h2','',p.title),node('div','detail',p.status==='sold'?'1 archived photo':(1+p.photos.length)+' photos'));const actions=node('div','actions'),view=node('button','',p.status==='sold'?'View saved photo':'View all photos');view.addEventListener('click',()=>openProduct(p));actions.append(view);content.append(actions);card.append(pic,content);el('grid').append(card);}if(!list.length)el('grid').append(node('p','empty',filter==='sold'?'No archived watches match. Watches appear here after their removal is detected during a successful refresh.':'No watches match these filters.'));}
el('search').addEventListener('input',()=>data&&render());el('brand').addEventListener('change',()=>data&&render());document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});if(data)render();}));el('close').addEventListener('click',()=>el('modal').close());el('modal').addEventListener('click',e=>{if(e.target===el('modal'))el('modal').close();});el('prev').addEventListener('click',()=>{if(index>0){index--;showPhoto();}});el('next').addEventListener('click',()=>{if(index<photos.length-1){index++;showPhoto();}});el('modal').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&index>0){index--;showPhoto();e.preventDefault();}if(e.key==='ArrowRight'&&index<photos.length-1){index++;showPhoto();e.preventDefault();}});
(async()=>{try{const response=await fetch('/catalog.json',{cache:'no-cache'});if(!response.ok)throw Error('Catalog unavailable');data=await response.json();if(data.version!==2||!Array.isArray(data.products))throw Error('Invalid catalog');for(const [status,label]of [['in_stock','In Stock'],['inbound','Inbound'],['sold','Archived']]){const box=node('div');box.append(node('strong','',String(data.products.filter(p=>p.status===status).length)),node('span','',label));el('stats').append(box);}for(const brand of [...new Set(data.products.map(p=>p.brand))].sort()){const option=node('option','',brand);option.value=brand;el('brand').append(option);}el('updated').textContent='Updated '+new Date(data.updated_at).toLocaleString();for(const s of data.sources){const a=node('a','',s.name+' source ↗');a.href=validUrl(s.url);a.target='_blank';a.rel='noopener noreferrer';a.style.marginRight='20px';el('sources').append(a);}render();}catch{el('resultcount').textContent='Could not load the collection.';el('grid').append(node('p','error','Please reload the page. If the problem continues, check the latest Vercel build.'));}})();

let swipeStart=null;el('viewer').addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')swipeStart={x:e.clientX,y:e.clientY};});el('viewer').addEventListener('pointerup',e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){if(dx<0&&index<photos.length-1)index++;else if(dx>0&&index>0)index--;showPhoto();}});el('viewer').addEventListener('pointercancel',()=>{swipeStart=null;});
